/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.libraryautomation;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class UserFrame extends JFrame {

    private JButton openBookListButton;
    private JButton borrowedBookButton;
    private JButton searchBookButton;
    private JButton userProfileButton;
    String username;
    
    public UserFrame(){
    
    }
    
    public UserFrame(String username) {
        this.username = username;
        // Frame ayarları
        setTitle("Kullanıcı Sayfası");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Panel oluştur
        JPanel panel = new JPanel();
        panel.setLayout(null);

        // Kitap listesini aç butonu
        openBookListButton = new JButton("Kitap Listesi");
        openBookListButton.setBounds(50, 30, 150, 25);
        panel.add(openBookListButton);

        // Kitap ödünç al butonu
        borrowedBookButton = new JButton("Ödünç Alınan Kitaplar");
        borrowedBookButton.setBounds(50, 70, 150, 25);
        panel.add(borrowedBookButton);

        // Kitap ara butonu
        searchBookButton = new JButton("Kitap Ara");
        searchBookButton.setBounds(250, 30, 100, 25);
        panel.add(searchBookButton);

        // Profil bilgileri butonu
        userProfileButton = new JButton("Profil Bilgileri");
        userProfileButton.setBounds(250, 70, 100, 25);
        panel.add(userProfileButton);

        // Butonlara action listener ekle
        openBookListButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Kitap listesi penceresini aç
                JOptionPane.showMessageDialog(null, "Kitap Listesi Açılıyor");
                // Kitap listesi frame kodu buraya eklenecek
                dispose();
                BookListFrame bookListFrame = new BookListFrame(username);
                bookListFrame.setVisible(true);
            }
        });

        borrowedBookButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Ödünç alın kitaplar penceresini aç
                dispose();
                JOptionPane.showMessageDialog(null, "Kitap Ödünç Alma Sayfası Açılıyor");
               
                new BorrowedBooks(username).setVisible(true);
                
                        
            }
        });

        searchBookButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Kitap ara penceresini aç
                JOptionPane.showMessageDialog(null, "Kitap Arama Sayfası Açılıyor");
                // Kitap ara frame kodu buraya eklenecek
                dispose();
                new SearchFrame(username).setVisible(true);
                

            }
        });

        userProfileButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Profil bilgileri penceresini aç
                JOptionPane.showMessageDialog(null, "Profil Bilgileri Sayfası Açılıyor");
                // Profil bilgileri frame kodu buraya eklenecek
                dispose();
                ProfileFrame ProfileFrame = new ProfileFrame(username);
                ProfileFrame.setVisible(true);
            }
        });

        // Paneli frame'e ekle
        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
